version: '3'
services:
  mongodb:
    image: mongo
    container_name: $MONGO_CONTAINER_NAME
    ports:
      - $MONGO_PORT
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  mongo-express:
    image: mongo-express
    container_name: $MONGO_EXPRESS_CONTAINER_NAME
    ports:
      - $MONGO_EXPRESS_PORT
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped